Allow for custom container element
inthepocket/cookie-though pull request #100
Opened 2021-07-02 09:23 UTC by thibmaek

2021-07-05 07:53 UTC, LukasCornille commented
Seems like a good idea! Could you add this new config variable to the [docs](https://github.com/inthepocket/cookie-though/blob/master/docs/jekyll/configuration.md) and the [types](https://github.com/inthepocket/cookie-though/blob/master/src/types.ts) and validate code coverage?

2021-07-05 08:32 UTC, thibmaek commented
For you I will do this @LukasCornille ! I already updated the types, and did the docs just now.

2021-07-06 05:21 UTC, LukasCornille commented
Looking good! Just the the tests appear to be failing at the moment 🙈.

2021-07-19 08:22 UTC, LukasCornille approved these changes

2021-07-19 08:25 UTC, LukasCornille commented
@thibmaek I've added 'aside' as the default element in case it's undefined in the defined config ;). 
Go ahead, so this has my stamp of approval peepoHappy

2021-07-19 11:45 UTC, gboston commented
Is there a reason to make this configurable?

2021-07-19 11:48 UTC, gboston requested changes

2021-07-19 11:48 UTC, gboston commented on docs/jekyll/configuration.md
> +* [containerElement](#containerElement)?
I would not allow to use other container elements.

2021-07-19 11:48 UTC, gboston commented on src/lib.ts
> +  const container = document.createElement(config.containerElement ?? 'aside');
Just use aside.

2021-07-19 11:50 UTC, LukasCornille commented
> Is there a reason to make this configurable, seems to be best practice to use aside?

This seems like a good idea, didn't think about this yet. I'll implement the changes.

2021-07-19 11:58 UTC, gboston approved these changes
lgtm

2021-07-19 12:09 UTC, PieterJanVdb approved these changes

2021-07-19 13:17 UTC, merged